# Generated by Django 3.1.3 on 2020-12-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='project/cover_images/'),
        ),
    ]
