# Generated by Django 3.1.3 on 2020-12-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(height_field='height', null=True, upload_to='project/cover_images/', width_field='width'),
        ),
    ]
