# Generated by Django 3.1.3 on 2021-01-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201227_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
