# Generated by Django 3.1.3 on 2020-12-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201205_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='project/cover_images/'),
        ),
    ]
