# Generated by Django 3.1.3 on 2021-01-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210123_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.FloatField(default=100, null=True),
        ),
    ]
