# Generated by Django 3.1.3 on 2021-01-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210124_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='projects.imagealbum'),
        ),
    ]
