# Generated by Django 3.1.3 on 2021-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210129_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quick_summary',
            field=models.CharField(default='', max_length=64),
        ),
    ]
