# Generated by Django 3.1.3 on 2021-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_quick_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='quick_summary',
            field=models.CharField(max_length=64),
        ),
    ]
