# Generated by Django 3.1.3 on 2020-12-15 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='introduction')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Introduction',
                'verbose_name_plural': 'Introduction',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutme')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.section')),
            ],
        ),
        migrations.CreateModel(
            name='IntroductionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=512)),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.introduction')),
            ],
        ),
    ]
