# Generated by Django 3.1.3 on 2020-12-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='aboutme'),
        ),
    ]
